### ISSUE TITLE
issue running the code

### ISSUE THREAD

**Issue by sayak1711** [ChrizH/pdfstructure#4]
I ran the following commands in a virtual environment with python 3.6.9 on Ubuntu system.

> git clone https://github.com/ChrizH/pdfstructure.git
> cd pdfstructure/
> python setup.py build
> python setup.py install
> pip install pdfminer
> pip install sortedcontainers

Then I ran this code from the examples in the readme on a PDF file of my own.

`from pdfstructure.hierarchy.parser import HierarchyParser
from pdfstructure.source import FileSource

path = "pdfpath..."
parser = HierarchyParser() 

source = FileSource(path) 
 
document = parser.parse_pdf(source)

from pdfstructure.printer import JsonFilePrinter
printer = JsonFilePrinter()
file_path = Path("test-pdf.json")

printer.print(document, file_path=str(file_path.absolute()))`

But I am getting this error

`(venv) parabole@parabole:~//$ python pdfstructure-test.py
Traceback (most recent call last):
  File "pdfstructure-test.py", line 1, in <module>
    from pdfstructure.hierarchy.parser import HierarchyParser
  File "//venv/lib/python3.6/site-packages/pdfstructure-0.0.1-py3.6.egg/pdfstructure/hierarchy/parser.py", line 6, in <module>
  File "//venv/lib/python3.6/site-packages/pdfstructure-0.0.1-py3.6.egg/pdfstructure/analysis/annotate.py", line 6, in <module>
  File "//venv/lib/python3.6/site-packages/pdfstructure-0.0.1-py3.6.egg/pdfstructure/analysis/sizemapper.py", line 5, in <module>
  File "//venv/lib/python3.6/site-packages/pdfstructure-0.0.1-py3.6.egg/pdfstructure/analysis/styledistribution.py", line 7, in <module>
  File "//venv/lib/python3.6/site-packages/pdfstructure-0.0.1-py3.6.egg/pdfstructure/utils.py", line 7, in <module>
ModuleNotFoundError: No module named 'pdfminer.high_level'`

**Comment by sayak1711** [comment]
Issue was resolved after uninstalling pdfminer and installing pdfminer.six

**Comment by ChrizH** [comment]
@sayak1711 thank you for testing the project! I will make sure to publish a stable version on pypi to make installation easier. 

Have you been able to get useful results using `pdfstructure`?
